const express = require("express");

const PORT = process.env.PORT || 3000;
const INDEX = "/index.html";

const server = express()
  .use(express.static("static"))   // Serve static content.
  .use(express.static("build"))    // Serve Javascripts generated by Browserify.
  .use(express.static("dist"))     // Serve Javascripts generated by parcel.
  .get("/", (req, res) => {
    res.redirect("index.html")
  })
  .listen(PORT, () => console.log(`Listening on ${PORT}`));
